train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_train_HR
      repeat: 10
      #cache: in_memory
      cache: none
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 96
      scale_max: 4
      augment: true
      sample_q: 9216
  batch_size: 4

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 10
      #cache: in_memory
      cache: none
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 96
      scale_max: 4
      sample_q: 9216
  batch_size: 4


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: edx
      args:
        scale: 2
        no_upsampling: false

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 10
epoch_val: 1
epoch_save: 2
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.9



