train_dataset:
  dataset:
    name: imageL0-folder
    args:
      hr_dir: data/selfWHURS/sobel/high-sobel-cross-train
      L0_dir: data/selfWHURS/smooth/smooth-whurs-train-grad-cross-high
      repeat: 3
      cache: in_memory
  wrapper:
    name: LO-wrappers
    args:
      inp_size: 96
      scale: 3
      augment: true
  batch_size: 10

val_dataset:
  dataset:
    name: imageL0-folder
    args:
      hr_dir: data/selfWHURS/sobel/high-sobel-test
      L0_dir: data/selfWHURS/smooth/smooth-whurs-test-high-grad
      repeat: 1
      cache: in_memory
  wrapper:
    name: LO-wrappers
    args:
      inp_size: 96
      scale: 3
  batch_size: 1


data_norm:
  lr: {sub: [0.5], div: [0.5]}
  ls: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: mkdg_high
  args:
    scale: 3



optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 500
epoch_val: 1
epoch_save: 100
multi_step_lr:
  milestones: [100, 200, 300, 400]
  gamma: 0.5



