train_dataset:
  dataset:
    name: imageL0-folder
    args:
      hr_dir: /home/ww020823/yxc/dataset/selfWHURS/sobel/high-sobel-cross-train
      L0_dir: /home/ww020823/yxc/dataset/selfWHURS/smooth-high-train-l0.2-k10-grad
      repeat: 3
      cache: none
  wrapper:
    name: LO-wrappers
    args:
      inp_size: 96
      scale: 2
      augment: true
  batch_size: 30

val_dataset:
  dataset:
    name: imageL0-folder
    args:
      hr_dir: /home/ww020823/yxc/dataset/selfWHURS/sobel/high-sobel-test
      L0_dir: /home/ww020823/yxc/dataset/selfWHURS/smooth-high-test-l0.2-k10-grad
      repeat: 1
      cache: none
  wrapper:
    name: LO-wrappers
    args:
      inp_size: 96
      scale: 2
  batch_size: 10


data_norm:
  lr: {sub: [0.5], div: [0.5]}
  ls: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: L0Smoothsam
  args:
    scale: 2
    upsampling: True


optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 500
epoch_val: 1
epoch_save: 100
multi_step_lr:
  milestones: [100, 200, 300, 400]
  gamma: 0.5



