test_dataset:
  dataset:
    name: imageL0-folder
    args:
      hr_dir: data/WHU-RS19-test/GT
      L0_dir: data/selfWHURS/smooth/smooth-whurs-test-grad
      repeat: 1
      cache: none
  wrapper:
    name: LO-wrappers
    args:
      scale: 4
  batch_size: 1

data_norm:
  lr: {sub: [0.5], div: [0.5]}
  ls: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}