test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: data/ITCVD\Test\patch
  wrapper:
    name: sr-paired
    args:
      scale: 2
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}