test_dataset:
  dataset:
    name: imageL0-folder
    args:
      hr_dir: /home/ww020823/yxc/dataset/WHU-RS19-test/GT
      L0_dir: /home/ww020823/yxc/dataset/smooth_whurs_test_grad
      repeat: 1
      cache: none
  wrapper:
    name: LO-wrappers
    args:
      inp_size: 96
      scale: 2
  batch_size: 10

data_norm:
  lr: {sub: [0.5], div: [0.5]}
  ls: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}