test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: load/selfWHURS/sobel/high-sobel-test
  wrapper:
    name: sr-paired
    args:
      scale: 4
  batch_size: 1

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}


