test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: data/ITCVD_patch/ITCVD_test_patch/X2
      root_path_2: data/ITCVD_patch/ITCVD_test_patch/HR
  wrapper:
    name: sr-implicit-paired
    args: {}
  batch_size: 1

eval_bsize: 30000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

