test_dataset:
  dataset:
    name: image-folder
    args:
      #root_path: E:\Code\Python\datas\RS\ITCVD_patch\ITCVD_test_patch
      root_path: /home/ww020823/yxc/dataset/ITCVD_patch/ITCVD_test_patch
  wrapper:
    name: sr-paired
    args:
      scale: 4
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}