test_dataset:
  dataset:
    name: imageL0-folder
    args:
      hr_dir: data/selfWHURS/sobel/low-sobel-test
      L0_dir: data/selfWHURS/smooth/smooth-whurs-test-low-grad
      cache: none
  wrapper:
    name: LO-wrappers
    args:
      scale: 2
  batch_size: 1

data_norm:
  lr: {sub: [0.5], div: [0.5]}
  ls: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}