test_dataset:
  dataset:
    name: imageL0-folder
    args:
      hr_dir: E:\Code\Python\datas\RS\WHU-RS19-train\GT
      L0_dir: E:\Code\Python\iPython\wavelet\smooth_whurs
  wrapper:
    name: LO-wrappers
    args:
      scale: 2
  batch_size: 10

data_norm:
  lr: {sub: [0.5], div: [0.5]}
  ls: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}