train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: data/selfRSSCN/RSSCN-train
      repeat: 1
      cache: in_memory
  wrapper:
    name: sr-paired
    args:
      inp_size: 48
      scale: 4
      augment: true
  batch_size: 30

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: data/selfRSSCN/RSSCN-test
      repeat: 1
      cache: in_memory
  wrapper:
    name: sr-paired
    args:
      inp_size: 48
      scale: 4
  batch_size: 10


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: pan
  args:
    scale: 4


optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 500
epoch_val: 1
epoch_save: 100
multi_step_lr:
  milestones: [100, 200, 300, 400]
  gamma: 0.5



