train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/WHU-RS19/WHU-RS19-train
      repeat: 10
      #cache: in_memory
      cache: none
  wrapper:
    name: sr-paired
    args:
      inp_size: 96
      scale: 2
      augment: true
  batch_size: 40

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/WHU-RS19/WHU-RS19-test
      first_k: 10
      repeat: 10
      #cache: in_memory
      cache: none
  wrapper:
    name: sr-paired
    args:
      inp_size: 96
      scale: 2
  batch_size: 10


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: edsr-baseline
  args:
    scale: 2
    no_upsampling: false

#resume: "save/WHURS19_LIIF(EDSR)X2/epoch-last.pth"

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1
epoch_val: 1
epoch_save: 10
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5



