train_dataset:
  dataset:
    name: image-folder
    args:
      #root_path: E:\Code\Python\datas\RS\ITCVD_patch\ITCVD_train_patch
      root_path: /home/ww020823/yxc/dataset/WHURS19/WHU-RS19-train
      repeat: 10
      #cache: in_memory
      cache: none
  wrapper:
    name: sr-paired
    args:
      inp_size: 48
      scale: 3
      augment: true
  batch_size: 48

val_dataset:
  dataset:
    name: image-folder
    args:
      #root_path: E:\Code\Python\datas\RS\ITCVD_patch\ITCVD_test_patch
      root_path: /home/ww020823/yxc/dataset/WHURS19/WHU-RS19-test
      first_k: 10
      repeat: 1
      #cache: in_memory
      cache: none
  wrapper:
    name: sr-paired
    args:
      inp_size: 48
      scale: 3
  batch_size: 8


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: drsenmkpa
  args:
    upsampling: true
    scale: 3

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 500
epoch_val: 1
epoch_save: 100
cosine_annealing_lr:
  T_max: 50

#multi_step_lr:
#  milestones: [100, 200, 300, 400]
#  gamma: 0.5



