train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: data/WHURS19/WHU-RS19-train
      repeat: 10
      cache: in_memory
  wrapper:
    name: sr-paired
    args:
      inp_size: 48
      scale: 3
      augment: true
  batch_size: 48

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: data/WHURS19/WHU-RS19-test
      repeat: 10
      cache: in_memory
  wrapper:
    name: sr-paired
    args:
      inp_size: 48
      scale: 3
  batch_size: 10


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: drsenpa
  args:
    upsampling: true
    scale: 3

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 500
epoch_val: 1
epoch_save: 100

#cosine_annealing_lr:
#  T_max: 50

multi_step_lr:
  milestones: [100, 200, 300, 400]
  gamma: 0.5



