train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: data/selfWHURS/sobel/high-sobel-train
      repeat: 1
      cache: in_memory
  wrapper:
    name: sr-paired
    args:
      inp_size: 48
      scale: 4
      augment: true
  batch_size: 40

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: data/selfWHURS/high-sobel-test
      repeat: 1
      cache: in_memory

  wrapper:
    name: sr-paired
    args:
      inp_size: 48
      scale: 4
  batch_size: 10


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: edsr-baseline
  args:
    scale: 4
    no_upsampling: false


optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 500
epoch_val: 1
epoch_save: 100
multi_step_lr:
  milestones: [100, 200, 300, 400]
  gamma: 0.5



