train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: data/selfAID/AID-train
      repeat: 1
      cache: none
  wrapper:
    name: sr-paired
    args:
      inp_size: 48
      scale: 4
      augment: true
  batch_size: 64

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: data/selfAID/AID-test
      repeat: 1
      cache: none
  wrapper:
    name: sr-paired
    args:
      inp_size: 48
      scale: 4
  batch_size: 16


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: psagrad
  args:
    n_resblocks: 20
    n_feats: 64
    scale: 4

resume: save/AID30_psagradx4/epoch-last.pth

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 100
epoch_val: 1
epoch_save: 20
multi_step_lr:
  milestones: [20, 40, 60, 80]
  gamma: 0.5



